### ISSUE TITLE
Make active edits transactional

### ISSUE THREAD

**Issue by gdbrown** [wb-crowdfusion/crowdfusion-active-edits#15]

**Comment by gdbrown** [comment]
classes should be (to match our conventions)

- ActiveEditRepository (no interface suffix)
- MySQLActiveEditRepository
- InMemoryActiveEditRepository (instead of cache since cache is not an implementation)

methods should be more precise (element can be confused with cf element for example).  ref or id would be more clear.

method `setMetaUpdate` is not entirely clear what that means.  maybe something less node specific as in `updatedField` or `touched` or `updatedPropery`.  also "setBlah" gets picked up by cf DI so there's sometimes a risk of that being injected with something unintentionally.

**Comment by excelwebzone** [comment]
@oefada can youdo some code  review and testing.. thanks.

**Comment by oefada** [comment]
@gdbrown , lets review.

**Comment by excelwebzone** [comment]
@oefada to prevent "owner" (original viewer) from seeing other users popup, you can add a small function to override the `b_saveandcontinue` click to pass a flag that will ignore the popup if other users where found

**Comment by excelwebzone** [comment]
```js
$('form#someForm').submit(function() {
  $(window).unbind('unload');

  //@todo pass hidden variable with form
});
```
